### ISSUE TITLE
get_bgp_config not working without peer groups

### ISSUE THREAD

**Issue by itdependsnetworks** [napalm-automation/napalm-eos#119]
### Description of Issue/Question

get_bgp_config not working without peer groups

### napalm-eos version
(Paste verbatim output from `pip freeze | grep napalm-eos` between quotes below)

```
napalm-eos==0.5.1

```

### eOS version
(Paste verbatim output from `show version | json` between quotes below)

```
eos-leaf1#show ver | json
{
    "modelName": "vEOS",
    "internalVersion": "4.15.5M-3054042.4155M",
    "systemMacAddress": "08:00:27:76:0f:74",
    "serialNumber": "",
    "memTotal": 1897592,
    "bootupTimestamp": 1484178092.29,
    "memFree": 78320,
    "version": "4.15.5M",
    "architecture": "i386",
    "internalBuildId": "d6560fe3-4c9f-4765-81f0-cba651cf54f8",
    "hardwareRevision": ""
}
eos-leaf1#

```

### Steps to Reproduce the Issue

BGP Configured without the use of peer groups: 

```
router bgp 104
   router-id 10.104.1.1
   timers bgp 5 15
   neighbor 10.10.10.19 remote-as 103
   neighbor 10.10.10.19 description Verizon
   neighbor 10.10.10.19 send-community
   neighbor 10.10.10.19 maximum-routes 12000
   network 10.104.1.0/24
   network 10.104.2.0/24
   network 10.104.3.0/24
   network 10.104.4.0/24
```

**Comment by mirceaulinic** [comment]
Hi @itdependsnetworks,

This is because it has been erroneously designed like that: http://napalm.readthedocs.io/en/latest/base.html#napalm_base.base.NetworkDriver.get_bgp_config
We can't change the output structure, as this is how napalm-base tests.

On the other hand, we can start discussing about a more correct method `get_oc_bgp_config` with respect to the OC model and deprecate this one.

**Comment by dbarrosop** [comment]
Yeah, this is something we should fix with a new method when we get the OC models up and running.

I am closing this one.

**Comment by itdependsnetworks** [comment]
Can we open this back up based on: https://github.com/napalm-automation/napalm-iosxr/pull/94/files

**Comment by mirceaulinic** [comment]
Sure @itdependsnetworks

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-eos/commit/6a0bf8d7d79a9eb038154aa23eb85a533066ce84
