### ISSUE TITLE
get_lldp_neighbors() works but not get_lldp_neighbors_detail()

### ISSUE THREAD

**Issue by narJH27** [napalm-automation/napalm-eos#127]
### Description of Issue/Question
I am using `get_lldp_neighbors_detail()` in my code to gather lldp stats from EOS devices. However, there are challenges in retrieving lldp detail info even though lldp has been enabled on the device and the output can be viewed using the cli command.

### Setup
Simple. IP connectivity to the device is available and transport is set to https.

### napalm-eos version
(Paste verbatim output from `pip freeze | grep napalm-eos` between quotes below)

```
napalm-eos==0.3.0
```

### eOS version
(Paste verbatim output from `show version | json` between quotes below)
Cannot paste the entire `show version` output due to legality issues.
```
"version": "4.15.5FX-7500R"
and
"version": "4.17.3F"
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
dev.get_lldp_neighbors_detail()

/Library/Python/2.7/site-packages/napalm_eos/eos.pyc in get_lldp_neighbors_detail(self, interface)
    523                         'remote_system_description'     : neighbor.get('systemDescription', u''),
    524                         'remote_chassis_id'             : neighbor.get('chassisId', u''),
--> 525                         'remote_system_capab'           : unicode(', '.join(capabilities)),
    526                         'remote_system_enable_capab'   : unicode(', '.join([capability for capability in capabilities.keys() if capabilities[capability]]))
    527                     }

TypeError: can only join an iterable
```

**Comment by mirceaulinic** [comment]
Hi @narJH27: how does the output look like? Can you please to see what's structurally different?
Thanks!

**Comment by narJH27** [comment]
@mirceaulinic you mean the CLI output ?

**Comment by mirceaulinic** [comment]
Yes: `show lldp neighbors detail | json`

**Comment by narJH27** [comment]
@mirceaulinic See below ...

The below output is for an interface that has no neighbor attached. 

```
    {
    "lldpNeighbors": {
        "EthernetYY/YY": {
            "lldpNeighborInfo": []
        }
      }
    }
```

The below output is for an interface that has a neighbor:

```
{
    "lldpNeighbors": {
        "EthernetYY/YY": {
            "lldpNeighborInfo": [
                {
                    "lastContactTime": xyz, 
                    "chassisId": "<mac_addr>", 
                    "managementAddresses": [], 
                    "lastChangeTime": abcd, 
                    "systemDescription": "<string output>", 
                    "ttl": <ttl>, 
                    "neighborDiscoveryTime": defg, 
                    "neighborInterfaceInfo": {
                        "portAndProtocolVlanEnabled": {}, 
                        "interfaceId": <str>, 
                        "autoNegAdvertisedCapabilities": [], 
                        "vlanNames": {}, 
                        "interfaceIdType": "interfaceName", 
                        "unknownTlvs": [], 
                        "unknownOrgDefinedTlvs": [], 
                        "protocolIdentityInfo": [], 
                        "portAndProtocolVlanSupported": {}
                    }, 
                    "chassisIdType": "<str>"
                }
            ]
        }
     } 
```

**Comment by colinmcintosh** [comment]
We're encountering this when remote systems don't send the LLDP systemCapabilities TLV (which isn't required by LLDP) but NAPALM expects it to always be there. This PR fixed it for us: https://github.com/napalm-automation/napalm-eos/pull/137

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-eos/commit/492f65ba1677e126ff1373886d1c1dd5ede32513
