### ISSUE TITLE
The current load methods do not allow aliases

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-eos#152]
### Description of Issue/Question

Not a bug, as this feature has been just introduced in pyeapi 0.8.0

+ other features for the `run_commands`: https://github.com/arista-eosplus/pyeapi/blob/master/pyeapi/client.py#L686-L687

EDIT: the features we can support are: `expandAliases` and `autoComplete`

**Comment by dbarrosop** [comment]
What is that? That sounds fairly new even on the eAPI itself, might break compatibility with older EOS versions?

**Comment by mirceaulinic** [comment]
They have been recently added in pyeapi, not sure about eAPI. I will investigate before trying to add this feature.

**Comment by dbarrosop** [comment]
Ok, not sure about the value of this anyway, I like that the `eapi` is picky and requires you to type full commands, otherwise it would be like python allowing you to write `device.load_m(...)` :P which might lead to issues if we implement some other method that starts with `load_m`.

**Comment by mirceaulinic** [comment]
Yes, perhaps `autoComplete` is arguably useful. But I believe `expandAliases` should be there though.

**Comment by dbarrosop** [comment]
What is `expandAliases`? I am afraid I am not familiar with it.
