### ISSUE TITLE
Loopback interfaces missing in get_facts()

### ISSUE THREAD

**Issue by inetuid** [napalm-automation/napalm-eos#16]
The show interfaces status command used to populate the interfaces list in get_facts() does not return any loopback interfaces. Is this intentional? Nothing in the docs/mailing list that I found that states they should be excluded.

**Comment by dbarrosop** [comment]
Hello,
Loopback interfaces should be there. Could you provide the output of the following commands, please?

`show version`, `show interfaces status`

Thanks

**Comment by inetuid** [comment]
As requested:

```
vEOS-S1.test#show version
Arista vEOS
Hardware version:
Serial number:
System MAC address:  000c.2982.8487

Software image version: 4.16.6M-3205780.4166M (engineering build)
Architecture:           i386
Internal build version: 4.16.6M-3205780.4166M
Internal build ID:      e796e94c-ba3b-4355-afcf-ef0abfbfaee3

Uptime:                 3 days, 3 hours and 39 minutes
Total memory:           1897592 kB
Free memory:            100704 kB


vEOS-S1.test#show interfaces status
Port       Name        Status       Vlan     Duplex Speed  Type            Flags
Et1        S1-L1       connected    routed   full   unconf EbraTestPhyPort
Et2        S1-L2       connected    routed   full   unconf EbraTestPhyPort
Ma1        Internal    connected    routed   a-full a-1G   10/100/1000


vEOS-S1.test#show interfaces description
Interface                      Status         Protocol Description
Et1                            up             up       S1-L1
Et2                            up             up       S1-L2
Lo0                            up             up
Lo666                          up             up       "This is a test"
Ma1                            up             up       Internal
```

**Comment by dbarrosop** [comment]
Ok, this one was easy. I fixed it on #19, would you mind testing the branch?

Thanks!

**Comment by inetuid** [comment]
The fix works for me at least - I now see the loopback interfaces in the output of get_facts():

`{'os_version': u'4.16.6M-3205780.4166M', 'uptime': 309722, 'interface_list': [u'Ethernet1', u'Ethernet2', u'Loopback0', u'Loopback666', u'Management1'], 'vendor': u'Arista', 'serial_number': u'', 'model': u'vEOS', 'hostname': u'vEOS-S1.test', 'fqdn': u'vEOS-S1.test.local'}`

**Comment by dbarrosop** [comment]
Great, thanks. I will try to release a patched version as soon as I can get @mirceaulinic or @fooelisa to approve my PR : )

**Comment by dbarrosop** [comment]
FYI napalm-eos 0.2.1 includes this bugfix
