### ISSUE TITLE
get_facts() does report internal OS version, not the OS version.

### ISSUE THREAD

**Issue by bholmgren** [napalm-automation/napalm-eos#177]
### Description of Issue/Question
get_facts() does report internal OS version, not the OS version.

I assume that is by choice but I believe that is an incorrect behaviour.

### napalm-eos version
(Paste verbatim output from `pip freeze | grep napalm-eos` between quotes below)

```
 # pip freeze | grep napalm-eos
napalm-eos==0.6.0
```

**Comment by mirceaulinic** [comment]
Hi @bholmgren - for posterity, could you please clarify here what is the internal version and what's the OS version? An example would be equally welcome. Thanks!

**Comment by bewing** [comment]
```
EOS# show version | grep version
Hardware version:    01.03
Software image version: 4.18.3.1F-2GB
Internal build version: 4.18.3.1F-2GB-5462878.41831F
```
get_facts() reports the Internal build version
https://github.com/napalm-automation/napalm-eos/blob/develop/napalm_eos/eos.py#L241

```python
In [8]: d.device.run_commands(["show version"])[0]['version']
Out[8]: '4.18.3.1F-2GB'

In [9]: d.device.run_commands(["show version"])[0]['internalVersion']
Out[9]: '4.18.3.1F-2GB-5462878.41831F'
```

**Comment by bholmgren** [comment]
Thanks @bewing. I think your comment explains it properly.

The trailing '-5462878.41831F' in this example is probably some internal build ID at Arista and not particularly useful for napalm users.

**Comment by dbarrosop** [comment]
We should keep it as it is. If you don't want the build version you can ignore it but that information is useful if you are running EFT images which some napalm users do.

**Comment by bholmgren** [comment]
For what it's worth, I'd like to offer a more detailed version of my view on this.

Ignoring build ID parts programatically is not as easy as one may think as the format of internal build ID is not fixed.
The best logic I've come up with so far is to strip everything from the last dash to the end but it is likely to be prone to errors and possible changes in the format.

While I understand why you prefer to keep the build ID rather than the OS version, my opinion is that a library should aim for correctness to be useful by the masses. Reporting an internal build ID as OS version simply does not seem like a correct behaviour.

If reporting a build ID is of value I suggest simply adding that as a separate field. If that breaks the data model concept one could always argue that a pragmatic way would be to include driver specific fields with keys starting with an underscore.

**Comment by ktbyers** [comment]
There are some issues on Cisco IOS as well.
- We need a way to add the feature set (things like advanced ip services, advanced security).
- Also IOS-XE has the dual numbering system.


Probably should factor this in to any changes to the `get_facts` data structure.

**Comment by dbarrosop** [comment]
My suggestion then is to do what's proposed here but adding a `vendor` key where we can add arbitrary k/v pairs for vendor specific stuff. We should postpone this and do it after the merge though.

**Comment by mirceaulinic** [comment]
Hi @bholmgren - we are currently in the process of reunification, please check https://napalm-automation.net/reunification/.
For the time being, we have moved this issue to https://github.com/napalm-automation/napalm/issues/436 so we can discuss further.
Going forward, we'd like to ask you to submit Pull Requests and Issue to the main repository: https://github.com/napalm-automation/napalm.

Thanks for understanding!
