### ISSUE TITLE
Can you use rollback()  if you have made changes using load_merge_candidate() ?

### ISSUE THREAD

**Issue by madhurabhogate** [napalm-automation/napalm-eos#181]
### napalm-eos version
(Paste verbatim output from `pip freeze | grep napalm-eos` between quotes below)

```

```

### eOS version
(Paste verbatim output from `show version | json` between quotes below)

```

```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

```

**Comment by dbarrosop** [comment]
shouldn't be a problem but I'd suggest validating first in the lab. To understand how it works check this:

https://napalm.readthedocs.io/en/latest/support/eos.html#rollback

**Comment by dbarrosop** [comment]
closing the issue, feel free to reopen if you think it's necessary.
