### ISSUE TITLE
get_bgp_neighbors_detail() not implemented

### ISSUE THREAD

**Issue by inetuid** [napalm-automation/napalm-eos#20]
May be on your development roadmap, but the get_bgp_neighbors_detail() is not implemented in the EOSDriver.

**Comment by jzohrab** [comment]
There are a few things not implemented for various drivers: http://napalm.readthedocs.io/en/latest/support/index.html#general-support-matrix

I think the team is getting to them as they get time.  If you can contribute, that would be good.  (I'm not part of the core team, but try to contribute when I can.)

**Comment by mirceaulinic** [comment]
Hi @inetuid, as you correctly supposed, `get_bgp_neighbors_detail` is scheduled to be implemented, but unfortunately I will not have the time earlier that end of July/beginning of August. If you need it earlier, and you are able to provide some code (or at least a starting point) please feel free to do so.

**Comment by inetuid** [comment]
I didn't know about the support matrix - thanks for the link. I'll look into providing some initial code for this.

**Comment by narJH27** [comment]
I am currently working on building this function. Will have something out soon.

**Comment by mirceaulinic** [comment]
Great, we are looking forward! Thanks!

**Comment by jzohrab** [comment]
Hey @narJH27, I'm doing the same for Nexus.  I've just started poking around and at the moment my branch is a total mess, I'll rebase and clean it up.  https://github.com/jzohrab/napalm-nxos/commits/wip_get_bgp_neighbors.  (actually, doing get_bgp_neighbors, not get_bgp_neighbors_detail ... whoops)

**Comment by dbarrosop** [comment]
Great! Let us know if we can help with something : )

**Comment by narJH27** [comment]
I do have a question. I am unable to retrieve the following pieces of information from the Arista box:

routing_table (string)
multihop (True/False)
multipath (True/False)
remove_private_as (True/False)
suppress_4byte_as (True/False)
local_as_prepend (True/False)
flap_count (int)

I have code ready that retrieves all the other fields per peer in the JSON structure proposed in base.py. Anyone has any ideas on how to retrieve these fields on EOS?

**Comment by mirceaulinic** [comment]
Hi @narJH27 can you please share the output from the device? Thanks!

**Comment by narJH27** [comment]
Please see the sample output below (apologies for the horrible formatting of the output):

switch>show ip bgp neighbors 10.0.2.6
BGP neighbor is 10.0.2.6, remote AS 64496, external link
BGP version 4, remote router ID 10.0.2.10
Negotiated BGP version 4
Last read 00:00:10, last write 00:00:58
Hold time is 180, keepalive interval is 60 seconds
BGP state is Established, up for 9d02h
Number of transitions to established: 1
Last state was OpenConfirm
Last event was RecvKeepAlive
Last error code was 0, last error subcode was 0
Neighbor Capabilities:
Multiprotocol IPv4 Unicast: advertised and received and negotiated
Route Refresh: advertised and received and negotiated
Message statistics:
InQ depth is 0
OutQ depth is 0
Sent Rcvd
Opens: 1 1
Notifications: 0 0
Updates: 1 269
Keepalives: 13087 13023
Route-Refresh: 0 0
Total messages: 13089 13293
Prefix statistics:
Total prefixes received 57
Inbound route map is prod-to-alpha
Outbound route map is alpha-to-prod
Local AS is 64511, local router ID 10.0.2.23
TTL is 0
Local TCP address is 10.0.2.5, local port is 59274
Remote TCP address is 10.0.2.6, remote port is 179
switch>

This has been taken from the config guide provided by Arista.

**Comment by mirceaulinic** [comment]
On yeah, there's not JSON equivalent and this text output is a bit of f**\* mess. It does not even look consistent between neighbors. 

You should use the following command to give you information about the VRF too:

```
sh ip bgp nei vrf all
```

This is what I see for a eBGP neighbor:

```
# show ip bgp nei 2.2.2.2
BGP neighbor is 2.2.2.2, remote AS 4436, external link
  BGP version 4, remote router ID 3.3.3.3, VRF default
  Inherits configuration from and member of peer-group my-group
  Negotiated BGP version 4
  Last read 00:00:00, last write 00:00:15
  Hold time is 90, keepalive interval is 30 seconds
  Configured hold time is 180, keepalive interval is 60 seconds
  Connect timer is inactive
  Idle-restart timer is inactive
  BGP state is Established, up for    6d16h
  Number of transitions to established: 1
  Last state was OpenConfirm
  Last event was RecvKeepAlive
  Neighbor Capabilities:
    Multiprotocol IPv4 Unicast: advertised and received and negotiated
    Four Octet ASN: advertised and received
    Route Refresh: advertised and received and negotiated
    Send End-of-RIB messages: advertised and received and negotiated
    Additional-paths Receive:
      IPv4 Unicast: advertised
  Restart timer is inactive
  End of rib timer is inactive
  Message statistics:
    InQ depth is 0
    OutQ depth is 0
                         Sent      Rcvd
    Opens:                  1         1
    Notifications:          0         0
    Updates:                7   1673979
    Keepalives:         19218     19799
    Route-Refresh:          0         0
    Total messages:     19226   1693779
  Prefix statistics:
                         Sent      Rcvd
    IPv4 Unicast:          44    587211
    IPv6 Unicast:           44         432675
  Inbound updates dropped by reason:
    AS path loop detection: 447
    Enforced First AS: 0
    Malformed MPBGP routes: 0
    Originator ID matches local router ID: 0
    Nexthop matches local IP address: 0
    Nexthop invalid for single hop eBGP: 0
  Inbound route map is policy-in
  Outbound route map is policy-out
  Inbound prefix list for IPv4 unicast is martians-v4
Local AS is 13335, local router ID 4.4.4.4
TTL is 1
Local TCP address is 5.5.5.5, local port is 179
Remote TCP address is 2.2.2.2, remote port is 62961
Auto-Local-Addr is disabled
Private AS number removed from outbound updates to this neighbor
TCP Socket Information:
  TCP state is ESTABLISHED
  Outgoing Maximum Segment Size (MSS): 1234
  Total Number of TCP retransmissions: 0
```

`VRF default` obviously gives you the value for `routing_table`.

For eBGP neighbor:

```
Nexthop matches local IP address: 0
Nexthop invalid for single hop eBGP: 0
```

For iBGP, only this:

```
Nexthop matches local IP address: 0
```

They both give you the information you need for `multihop`.

**Comment by narJH27** [comment]
Ok. What about the rest of the fields?

**Comment by mirceaulinic** [comment]
For `multipath` I don't know how it should look like (probably is displayed when used). I will check also for `local_as_prepend` and  `remove_private_as`. You should set `False` as default value for all of them as they may or may not be there. The same for `suppress_4byte_as`, but I don't know if Arista can do that.
For `flap_count` _perhaps_ you can use `Number of transitions to established: 1`, although I would say t's the states it went through to Established.

**Comment by narJH27** [comment]
@mirceaulinic Funny thing is that I do not see the:

`Nexthop matches local IP address: 0
Nexthop invalid for single hop eBGP: 0`

on any of my EBGP peers. The OS version I am using is 4.15.2F. Maybe these fields are only displayed in certain OS versions?

**Comment by dbarrosop** [comment]
@narJH27 In case of doubt, just set it to False and we can build on that later on. Just add a docstring on the method explaining which attributes you are not extracting properly.

**Comment by mirceaulinic** [comment]
@narJH27 I'm running 4.15.5F, but this should not make any difference.
Anyway, you can search for `Nexthop matches local IP address:`. When is not found or the value is 0, `multihop=False`, otherwise is `True`.
BTW: in NAPALM we've integrated [TextFSM](https://github.com/google/textfsm) to parse this kind of text outputs.
E.g.: for an output like [this](https://github.com/google/textfsm/blob/master/examples/juniper_bgp_summary_example) you'd need to place a template like [this](https://github.com/google/textfsm/blob/master/examples/juniper_bgp_summary_template) under [napalm_eos/utils/textfsm_templates](https://github.com/napalm-automation/napalm-eos/tree/develop/napalm_eos/utils/textfsm_templates).
It's a bit tricky at the beginning, but way more powerful than parsing the raw text yourself.

**Comment by narJH27** [comment]
@dbarrosop and @mirceaulinic Thanks for the tip. I was using textfsm anyways to parse my outputs :)
I will be pushing the patch soon. I have not been able to retrieve 5 fields and have defaulted the values to False or 0. Also, there is a TODO in the method specifying that this needs to be resolved going ahead.

**Comment by narJH27** [comment]
Pushed my changes. Please feel free to integrate when you feel so fit.

**Comment by mirceaulinic** [comment]
This can be closed once https://github.com/napalm-automation/napalm-eos/pull/30 is merged
