### ISSUE TITLE
Deprecation of get_ntp_peers

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-eos#29]
Some time ago I noticed that Aristas are pretty different when it comes to NTP. It is possible to set NTP servers but cannot establish peerings with other devices.
I am going soon enough to propose the method that retrieves the NTP servers configured on the device: `get_ntp_servers` (base ref: https://github.com/napalm-automation/napalm-base/pull/36).

What would be the best thing to do with the current `get_ntp_peers`? Should return empty `dict` or raise `NotImplementedError`?

**Comment by dbarrosop** [comment]
If it's not supported I'd rather return and empty dict. I did the same for lldp_neighbors and fortios, for example.

**Comment by dbarrosop** [comment]
Fixed by #34
