### ISSUE TITLE
KeyError when executing get_bgp_neighbors

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-eos#58]
### Description of Issue/Question

Same issue as #53, for `get_bgp_neighbors` this time - I should have thought.
### napalm-eos version

0.3.0
### Network OS version

any
### Steps to Reproduce the Issue

Execute `get_bgp_neighbors`
### Error Traceback

(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/state/home/mircea/napalm-eos/napalm_eos/eos.py", line 1302, in get_bgp_neighbors
    [peer_info['remote_address']]['prefixAccepted'])
KeyError: u'1.2.3.4'
```

**Comment by dbarrosop** [comment]
Same here, could you add a test case for this in #69?

Thanks!

**Comment by mirceaulinic** [comment]
Sure, I'll add them

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-eos/pull/69
