### ISSUE TITLE
.get_route_to() throwing uncatched errror

### ISSUE THREAD

**Issue by bewing** [napalm-automation/napalm-eos#98]
### Description of Issue/Question
When attempting to get information about a connected route, an error is thrown
### Setup
None
### napalm-eos version

(Paste verbatim output from `pip freeze | grep napalm-eos` between quotes below)

```
napalm-eos==0.5.0
```

### eOS version
(Paste verbatim output from `show version | json` between quotes below)

```
{
    "modelName": "vEOS",
    "internalVersion": "4.16.6M-3205780.4166M",
    "systemMacAddress": "00:15:5d:1b:db:cf",
    "serialNumber": "",
    "memTotal": 1897592,
    "bootupTimestamp": 1480670690.0,
    "memFree": 92896,
    "version": "4.16.6M",
    "architecture": "i386",
    "isIntlVersion": false,
    "internalBuildId": "e796e94c-ba3b-4355-afcf-ef0abfbfaee3",
    "hardwareRevision": ""
}
```

### Steps to Reproduce the Issue
Attempt to get_route_to() directly connected route
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm_base import get_network_driver
>>> import pprint,getpass
>>> password = getpass.getpass()
Password:
>>> driver = get_network_driver('eos')
>>> device = driver('10.192.100.86', 'bewing', password)
>>> device.open()
>>> device.get_route_to(u'172.16.185.5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "napalm_eos/eos.py", line 1071, in get_route_to
    'next_hop': napalm_base.helpers.ip(next_hop.get('nexthopAddr')),
  File "/home/bewing/napalm-eos/local/lib/python2.7/site-packages/napalm_base/helpers.py", line 242, in ip
    return py23_compat.text_type(IPAddress(addr))
  File "/home/bewing/napalm-eos/local/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 306, in __init__
    'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from None

```

JSON from the router for "show ip route":
```
localhost#show ip route 172.16.185.0 | json
{
    "vrfs": {
        "default": {
            "routes": {
                "172.16.185.0/24": {
                    "kernelProgrammed": true,
                    "directlyConnected": true,
                    "routeAction": "forward",
                    "vias": [
                        {
                            "interface": "Ethernet1"
                        }
                    ],
                    "hardwareProgrammed": true,
                    "routeType": "connected"
                }
            },
            "allRoutesProgrammedKernel": true,
            "routingDisabled": false,
            "allRoutesProgrammedHardware": true,
            "defaultRouteState": "reachable"
        }
    }
}
```

**Comment by bewing** [comment]
Do we want to return None, an empty string, or just leave the key unset for a directly connected route's nextHop?

**Comment by mirceaulinic** [comment]
When calling this method you should specify the protocol too. This implementation does not really reflect that, but for reference see: https://github.com/napalm-automation/napalm-junos/blob/develop/napalm_junos/junos.py#L961

So, if you do ```device.get_route_to(u'172.16.185.5', 'bgp')``` won't be displayed any connected routes.

So, in order to follow the same implementation patters as for JunOS and IOS-XR, we need to make the protocol arg mandatory and use it to filter out any route learned through a different protocol.

**Comment by bewing** [comment]
Why would we not want to support connected routes?  They are present in the route table.  Should it not be a supported type, with an empty string for next_hop?

Furthermore, the base implementation states that protocol is optional, and infers that leaving it blank would search all route types.

**Comment by mirceaulinic** [comment]
> Why would we not want to support connected routes?

I didn't say that. I said that if you request BGP routes, only BGP routes will be returned.

> Furthermore, the base implementation states that protocol is optional, and infers that leaving it blank would search all route types.

If napalm-base says that, then we should leave it. It also makes more sense to me and we need to fix JunOS and IOS-XR then accordingly.

**Comment by dbarrosop** [comment]
> If napalm-base says that, then we should leave it. It also makes more sense to me and we need to fix JunOS and IOS-XR then accordingly.


Problem with that is that we are actually lying. We don't support everything. Or are we planning to support any potential IGP plus BGP on any platform? The benefit of forcing to ask for a platform is that if someone asks for EIGRP on IOS we can just say `sorry Notimplemented for protocol EIGRP` but if we allow None to signal we want everything we might be lying for those running EIGRP/RIPor any other protocol we are not parsing.

I would actually change base and state that protocol is mandatory. Thoughts?

**Comment by bewing** [comment]
> I would actually change base and state that protocol is mandatory. Thoughts?

I personally would prefer the ability to utilize get_route_to() to get the state of the FIB, so being able to query without a protocol is highly desired.  If we want to implement another method to get forwarding state, that would work as well.

**Comment by dbarrosop** [comment]
Another problem is that `napalm_base` says that `get_route_to` _"Returns a dictionary of dictionaries containing details of all available routes to a destination"_ but looks like we are only checking the installed routes. That's is contradictory with the description of the method and the fact that we have a field called `current_active` and `inactive_reason`.

> If we want to implement another method to get forwarding state, that would work as well

Yes, I think that would make more sense. Either that or modify this one. Let's wait and see what @mirceaulinic thinks as he is the one that came up with this method.

**Comment by mirceaulinic** [comment]
> Another problem is that napalm_base says that get_route_to "Returns a dictionary of dictionaries containing details of all available routes to a destination" but looks like we are only checking the installed routes. That's is contradictory with the description of the method and the fact that we have a field called current_active and inactive_reason.

True :) I think we should change the docstring in that case - I we should return all possible installed routes.

> If we want to implement another method to get forwarding state, that would work as well

Yes, I agree on this point.

**Comment by mirceaulinic** [comment]
> I would actually change base and state that protocol is mandatory. Thoughts?

No - by default I would find easier to be able to retrieve all learned routes to a destination. And also to filter by a protocol if possible, but not make this mandatory.

**Comment by dbarrosop** [comment]
I personally think we should deprecate this method. I think we should have a method like:

```get_forwarding_information_for(ip_net=None)```

Which only returns forwarding information; prefix, prefix-length, next-hop, next-hop-interface

And then have protocol specific methods:

```
get_bgp_route(ip_net=None)
get_ospf_route(ip_net=None)
get_isis_route(ip_net=None)
get_eigrp_route(ip_net=None)
...
```

And then include more protocol-relevant information on those.

The reason I want to deprecate this one is because it's too overly complex and I think it's lying to the user as it gives a false expectation on the information it might return.

**Comment by bewing** [comment]
> Which only returns forwarding information; prefix, prefix-length, next-hop, next-hop-interface

Are you specifically excluding listing what RIB/protocol sourced the installed route?  Because I still feel that would be relevant information.

**Comment by dbarrosop** [comment]
The FIB doesn't know/care about it but I guess we could include that info anyway as that might help then checking for more information with another method.

In any case, this was just a generic proposal. If we decide to go down this path we will need a proper discussion on a dedicated issue/PR potentially looking at the OC implementation to see if it makes sense implementing their model.

**Comment by mirceaulinic** [comment]
> I personally think we should deprecate this method.

No, I don't agree. I think we should keep them both (at least for a while).

> get_forwarding_information_for(ip_net=None)

Can we move this please in ```napalm-base```? I think we'll have many to discuss about that as, again, that's another complex example.

**Comment by dbarrosop** [comment]
> No, I don't agree. I think we should keep them both (at least for a while).

With deprecating I meant raising a DeprecationWarning exception which doesn't really fail your program but prints a noisy Warning that you should stop using it in favor of something else.

https://docs.python.org/2/library/warnings.html#module-warnings
